In [1]:
import pandas as pd

NBA = pd.read_csv('C:/master/Pràctica II Visualització/NBA.csv')

In [2]:
NBA.head(5)

,GAME_DATE_EST,GAME_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,...,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,TEAM_ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,YEAR
0,2021-05-26,42000102,1610612755,1610612764,120.0,0.557,0.684,0.429,26.0,45.0,...,0.402,0.633,0.091,22.0,40.0,WAS,Wizards,1961,Washington,2021
1,2021-05-26,42000102,1610612755,1610612764,120.0,0.557,0.684,0.429,26.0,45.0,...,0.402,0.633,0.091,22.0,40.0,WAS,Wizards,1961,Washington,2021
2,2021-05-26,42000102,1610612755,1610612764,120.0,0.557,0.684,0.429,26.0,45.0,...,0.402,0.633,0.091,22.0,40.0,WAS,Wizards,1961,Washington,2021
3,2021-05-26,42000102,1610612755,1610612764,120.0,0.557,0.684,0.429,26.0,45.0,...,0.402,0.633,0.091,22.0,40.0,WAS,Wizards,1961,Washington,2021
4,2021-05-26,42000102,1610612755,1610612764,120.0,0.557,0.684,0.429,26.0,45.0,...,0.402,0.633,0.091,22.0,40.0,WAS,Wizards,1961,Washington,2021

In [3]:
NBA['NICKNAME'].unique()

array(['Wizards', '76ers', 'Hawks', 'Knicks', 'Grizzlies', 'Jazz',
       'Celtics', 'Nets', 'Lakers', 'Suns', 'Mavericks', 'Clippers',
       'Heat', 'Bucks', 'Trail Blazers', 'Nuggets', 'Warriors', 'Pacers',
       'Spurs', 'Hornets', 'Raptors', 'Rockets', 'Cavaliers', 'Magic',
       'Pistons', 'Bulls', 'Timberwolves', 'Pelicans', 'Thunder', 'Kings'],
      dtype=object)

In [4]:
nba = NBA.groupby(['NICKNAME', 'YEAR']).agg({'PTS_home': 'sum', 'PTS_away': 'sum', 'AST_home': 'sum', 'AST_away': 'sum', 'REB_home': 'sum', 'REB_away': 'sum', 'FG_PCT_home': 'mean', 'FG_PCT_away': 'mean', 'FT_PCT_home': 'mean', 'FT_PCT_away': 'mean', 'FG3_PCT_home': 'mean', 'FG3_PCT_away': 'mean'})

nba.columns = ['Total PTS_home', 'Total PTS_away', 'Total AST_home', 'Total AST_away', 'Total REB_home', 'Total REB_away', 'FG_PCT_home', 'FG_PCT_away', 'FT_PCT_home', 'FT_PCT_away', 'FG3_PCT_home', 'FG3_PCT_away']
nba = nba.reset_index()

nba.head(6)

,NICKNAME,YEAR,Total PTS_home,Total PTS_away,Total AST_home,Total AST_away,Total REB_home,Total REB_away,FG_PCT_home,FG_PCT_away,FT_PCT_home,FT_PCT_away,FG3_PCT_home,FG3_PCT_away
0,76ers,2019,138681.0,133732.0,31497.0,29407.0,55593.0,54766.0,0.468036,0.455428,0.765727,0.756807,0.351800,0.343857
1,76ers,2020,79726.0,75886.0,17012.0,16543.0,33015.0,31487.0,0.464743,0.440236,0.773814,0.747288,0.347621,0.351432
2,76ers,2021,110229.0,106136.0,24375.0,21751.0,42743.0,42187.0,0.480141,0.458087,0.755653,0.768579,0.386255,0.346421
3,Bucks,2019,153352.0,149998.0,34614.0,32685.0,65131.0,64108.0,0.451870,0.447169,0.735990,0.762311,0.362640,0.353297
4,Bucks,2020,100520.0,98644.0,22288.0,20398.0,41823.0,40867.0,0.459879,0.439784,0.771628,0.794287,0.371561,0.343498
5,Bucks,2021,112559.0,110045.0,24532.0,23612.0,45136.0,42370.0,0.474431,0.467805,0.753864,0.787775,0.394252,0.366428

In [5]:
points = nba['Total PTS_home'] + nba['Total PTS_away']
assists = nba['Total AST_home'] + nba['Total AST_away']
rebounds = nba['Total REB_home'] + nba['Total REB_away']
FG_PCT = (nba['FG_PCT_home'] + nba['FG_PCT_away'])/2
FT_PCT = (nba['FT_PCT_home'] + nba['FT_PCT_away'])/2
FG3_PCT = (nba['FG3_PCT_home'] + nba['FG3_PCT_away'])/2

nba['Total PTS'] = points
nba['Total AST'] = assists
nba['Total REB'] = rebounds
nba['Field Goal %'] = FG_PCT
nba['Free Throw %'] = FT_PCT
nba['3-point Field Goal %'] = FG3_PCT

nba.head(6)

,NICKNAME,YEAR,Total PTS_home,Total PTS_away,Total AST_home,Total AST_away,Total REB_home,Total REB_away,FG_PCT_home,FG_PCT_away,FT_PCT_home,FT_PCT_away,FG3_PCT_home,FG3_PCT_away,Total PTS,Total AST,Total REB,Field Goal %,Free Throw %,3-point Field Goal %
0,76ers,2019,138681.0,133732.0,31497.0,29407.0,55593.0,54766.0,0.468036,0.455428,0.765727,0.756807,0.351800,0.343857,272413.0,60904.0,110359.0,0.461732,0.761267,0.347828
1,76ers,2020,79726.0,75886.0,17012.0,16543.0,33015.0,31487.0,0.464743,0.440236,0.773814,0.747288,0.347621,0.351432,155612.0,33555.0,64502.0,0.452490,0.760551,0.349527
2,76ers,2021,110229.0,106136.0,24375.0,21751.0,42743.0,42187.0,0.480141,0.458087,0.755653,0.768579,0.386255,0.346421,216365.0,46126.0,84930.0,0.469114,0.762116,0.366338
3,Bucks,2019,153352.0,149998.0,34614.0,32685.0,65131.0,64108.0,0.451870,0.447169,0.735990,0.762311,0.362640,0.353297,303350.0,67299.0,129239.0,0.449519,0.749150,0.357968
4,Bucks,2020,100520.0,98644.0,22288.0,20398.0,41823.0,40867.0,0.459879,0.439784,0.771628,0.794287,0.371561,0.343498,199164.0,42686.0,82690.0,0.449832,0.782958,0.357530
5,Bucks,2021,112559.0,110045.0,24532.0,23612.0,45136.0,42370.0,0.474431,0.467805,0.753864,0.787775,0.394252,0.366428,222604.0,48144.0,87506.0,0.471118,0.770820,0.380340

In [6]:
nba.drop('Total PTS_home', inplace=True, axis=1)
nba.drop('Total PTS_away', inplace=True, axis=1)
nba.drop('Total AST_home', inplace=True, axis=1)
nba.drop('Total AST_away', inplace=True, axis=1)
nba.drop('Total REB_home', inplace=True, axis=1)
nba.drop('Total REB_away', inplace=True, axis=1)
nba.drop('FG_PCT_home', inplace=True, axis=1)
nba.drop('FG_PCT_away', inplace=True, axis=1)
nba.drop('FT_PCT_home', inplace=True, axis=1)
nba.drop('FT_PCT_away', inplace=True, axis=1)
nba.drop('FG3_PCT_home', inplace=True, axis=1)
nba.drop('FG3_PCT_away', inplace=True, axis=1)

In [7]:
nba.head(6)

,NICKNAME,YEAR,Total PTS,Total AST,Total REB,Field Goal %,Free Throw %,3-point Field Goal %
0,76ers,2019,272413.0,60904.0,110359.0,0.461732,0.761267,0.347828
1,76ers,2020,155612.0,33555.0,64502.0,0.452490,0.760551,0.349527
2,76ers,2021,216365.0,46126.0,84930.0,0.469114,0.762116,0.366338
3,Bucks,2019,303350.0,67299.0,129239.0,0.449519,0.749150,0.357968
4,Bucks,2020,199164.0,42686.0,82690.0,0.449832,0.782958,0.357530
5,Bucks,2021,222604.0,48144.0,87506.0,0.471118,0.770820,0.380340

In [8]:
nba.shape

(90, 8)

In [10]:
nba.to_csv('C:/master/Pràctica II Visualització/NBA_Clear.csv', index=False, header=True)